//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stone.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public decimal Amount { get; set; }
        public int Type { get; set; }
        public int CardID { get; set; }
        public int Number { get; set; }
    
        public virtual Card Card { get; set; }
    }
}
